
title: Village 2036
tagline:  'La passion des données'
email: implication@village2036.org
description: >- # this means to ignore newlines until "baseurl:"
  Une communauté collaborative pour comprendre et expliquer les données ouvertes et publiques.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
logo: /public/logos/workinprogressmap.png

paginate:            5
permalink:           pretty

plugins:
  - jekyll-paginate

github:
  repo: "https://github.com/village2036/www/"


collections:
  posts:
    output: true
  enquetes:
    output: true

exclude:
  - readme.md
